openapi: 3.0.0
info:
  title: Products API 
  version: 1.0.0
  description: API Managing Products
servers:
  - url: http://localhost:5000
paths:
  /api/v1/products:
    get:
      summary: Example endpoint
      description: This is an example endpoint
      responses:
        '200':
          description: Successful response
