openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
# components:
#   securitySchemes:
#     Authorization:
#       type: http
#       scheme: bearer
#       bearerFormat: JWT
#       value: "Bearer <JWT token here>"
# paths:
#   /protected-route:
#     get:
#       summary: This route requires a JWT token
#       security:
#         - bearerAuth: []
#       responses:
#         '200':
#           description: Successful response
#         '401':
#           description: Unauthorized
