openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0


paths:
  /api/products:
    get:
      tags:
        - Products Routes
      security:
        - Authorization: []
      summary: Get a list of products
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: size
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  page:
                    type: integer
                  size:
                    type: integer
                  dataSize:
                    type: integer
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                        name:
                          type: string
                        price:
                          type: number
                        images:
                          type: array
                          items:
                            type: string
              example:
                message: all products returned successfully
                page: 2
                size: 1
                dataSize: 1
                data:
                  - _id: "669821775a742bb5471afb15"
                    name: "apple watch"
                    price: 1200
                    images: []

    post:
      tags:
        - Products Routes
      security:
        - Authorization: []
      summary: Add a new product (admin only)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: iphone 14
                description:
                  type: string
                  example: iphone 14 with 256 GB memory
                price:
                  type: number
                  example: 1000
                stock:
                  type: integer
                  example: 100
                brand:
                  type: string
                  example: Apple
                images:
                  type: array
                  items:
                    type: string
                    example: 66980b787ff6796d6d9b84da
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                      description:
                        type: string
                      price:
                        type: number
                      stock:
                        type: integer
                      images:
                        type: array
                        items:
                          type: string
                      _id:
                        type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      __v:
                        type: integer
              example:
                message: product created successfully
                data:
                  name: "apple watch"
                  description: "watch"
                  price: 1200
                  stock: 10
                  images:
                    - "66980b787ff6796d6d9b84da"
                  _id: "66992d0dace2115bac5fe371"
                  createdAt: "2024-07-18T14:56:13.652Z"
                  updatedAt: "2024-07-18T14:56:13.652Z"
                  __v: 0

  /api/products/{id}:
    get:
      tags:
        - Products Routes
      summary: Get product details by ID
      security:
        - Authorization: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                      description:
                        type: string
                      price:
                        type: number
                      stock:
                        type: integer
                      images:
                        type: array
                        items:
                          type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      __v:
                        type: integer
              example:
                message: product details showed successfully
                data:
                  _id: "66992d0dace2115bac5fe371"
                  name: "apple watch"
                  description: "watch"
                  price: 1200
                  stock: 10
                  images:
                    - "66980f540afb6a30921e7cc9"
                    - "66980f540afb6a30921e7cc9"
                    - "66980f540afb6a30921e7cc9"
                    - "66980b787ff6796d6d9b84da"
                    - "66980f540afb6a30921e7cc9"
                  createdAt: "2024-07-18T14:56:13.652Z"
                  updatedAt: "2024-07-18T15:48:17.098Z"
                  __v: 0

    put:
      tags:
        - Products Routes
      summary: Update product details (admin only)
      security:
        - Authorization: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  exmple: updated name
                description:
                  type: string
                  example: updated description
                price:
                  type: number
                  example: 1500
                stock:
                  type: integer
                  example: 10
                brand:
                  type: string
                  example: apple
                addImages:
                  type: array
                  items:
                    type: string
                    example: 669a4e2cfe290fe39eaee244
                deleteImages:
                  type: array
                  example: 66980b787ff6796d6d9b84da
                  items:
                    type: string
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                      description:
                        type: string
                      price:
                        type: number
                      stock:
                        type: integer
                      images:
                        type: array
                        items:
                          type: string
                      createdAt:
                        type: string
                      updatedAt:
                        type: string
                      __v:
                        type: integer
              example:
                message: Product updated successfully
                data:
                  _id: "66992d0dace2115bac5fe371"
                  name: "apple watch"
                  description: "watch"
                  price: 1200
                  stock: 10
                  images:
                    - "66980f540afb6a30921e7cc9"
                    - "66980f540afb6a30921e7cc9"
                    - "66980f540afb6a30921e7cc9"
                    - "66980b787ff6796d6d9b84da"
                    - "66980f540afb6a30921e7cc9"
                  createdAt: "2024-07-18T14:56:13.652Z"
                  updatedAt: "2024-07-18T15:48:17.098Z"
                  __v: 0
      

    delete:
      tags:
        - Products Routes
      summary: Delete a product (admin only)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Product deleted successfully
      security:
        - Authorization: []
